libFirm: Linked Lists
Linked Lists
Abstract Data Structures
Doubly linked lists.
Defines
#define LIST_HEAD_INIT(name) { &(name), &(name) }
Static initializer for a list header.
#define LIST_HEAD(name) struct list_head name = LIST_HEAD_INIT(name)
Defines a (static) list reference.
#define INIT_LIST_HEAD(ptr)
Initializes a list header.
#define list_entry(ptr, type, member) _list_container_of(ptr, type, member)
list_entry - get the struct for this entry
#define list_for_each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
list_for_each - iterate over a list
#define __list_for_each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
__list_for_each - iterate over a list
#define list_for_each_prev(pos, head) for (pos = (head)->prev; pos != (head); pos = pos->prev)
list_for_each_prev - iterate over a list backwards
#define list_for_each_safe(pos, n, head)
list_for_each_safe - iterate over a list safe against removal of list entry
#define list_for_each_entry(type, pos, head, member)
list_for_each_entry - iterate over list of given type
#define list_for_each_entry_reverse(type, pos, head, member)
list_for_each_entry_reverse - iterate backwards over list of given type.
#define list_for_each_entry_safe(type, pos, n, head, member)
list_for_each_entry_safe - iterate over list of given type safe against removal of list entry
Typedefs
typedef struct list_head list_head
List Header.
Functions
static void __list_add (struct list_head *new_node, struct list_head *prev, struct list_head *next)
Inserts a new entry between two known consecutive entries.
static void list_add (struct list_head *new_node, struct list_head *head)
Adds a new entry.
static void list_add_tail (struct list_head *new_node, struct list_head *head)
Adds a new entry.
static void __list_del (struct list_head *prev, struct list_head *next)
Deletes a list entry by making the prev/next entries point to each other.
static void list_del (struct list_head *entry)
Deletes entry from list.
static void list_del_init (struct list_head *entry)
Deletes entry from list and reinitialize it.
static void list_move (struct list_head *list, struct list_head *head)
Deletes from one list and add as another's head.
static void list_move_tail (struct list_head *list, struct list_head *head)
Deletes from one list and add as another's tail.
static int list_empty (const struct list_head *head)
Tests whether a list is empty.
static void __list_splice (struct list_head *list, struct list_head *head)
Join two nonempty lists.
static void list_splice (struct list_head *list, struct list_head *head)
list_splice - join two lists
static void list_splice_init (struct list_head *list, struct list_head *head)
list_splice_init - join two lists and reinitialize the emptied list.
Detailed Description
Doubly linked lists.
Simple doubly linked list implementation.
Some of the internal functions ("__xxx") are useful when manipulating whole lists rather than single entries, as sometimes we already know the next/prev entries and we can generate better code by using them directly rather than using the generic single-entry routines.
Define Documentation
#define __list_for_each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
__list_for_each - iterate over a list
Parameters:
pos the &struct list_head to use as a loop counter.
head the head for your list.
This variant differs from list_for_each() in that it's the simplest possible list iteration code, no ing is done. Use this for code that knows the list to be very short (empty or 1 entry) most of the time.
Definition at line 241 of file list.h.
#define INIT_LIST_HEAD (ptr)
Value:
do { \
    (ptr)->next = (ptr); (ptr)->prev = (ptr); \
} while (0)
Initializes a list header.
Definition at line 37 of file list.h.
Referenced by list_del_init(), and list_splice_init().
#define list_entry (ptr, type, member) _list_container_of(ptr, type, member)
list_entry - get the struct for this entry
Parameters:
ptr the &struct list_head pointer.
type the type of the struct this is embedded in.
member the name of the list_struct within the struct.
Definition at line 220 of file list.h.
#define list_for_each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
list_for_each - iterate over a list
Parameters:
pos the &struct list_head to use as a loop counter.
head the head for your list.
Definition at line 228 of file list.h.
#define list_for_each_entry (type, pos, head, member)
Value:
for (pos = list_entry((head)->next, type, member);  \
         &pos->member != (head);                        \
         pos = list_entry(pos->member.next, type, member))
list_for_each_entry - iterate over list of given type
Parameters:
type the type of the struct where the listhead is embedded in
pos the type * to use as a loop counter.
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 269 of file list.h.
#define list_for_each_entry_reverse (type, pos, head, member)
Value:
for (pos = list_entry((head)->prev, type, member);       \
         &pos->member != (head);                             \
         pos = list_entry(pos->member.prev, type, member))
list_for_each_entry_reverse - iterate backwards over list of given type.
Parameters:
type the type of the struct where the listhead is embedded in
pos the type * to use as a loop counter.
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 281 of file list.h.
#define list_for_each_entry_safe (type, pos, n, head, member)
Value:
for (pos = list_entry((head)->next, type, member),       \
        n = list_entry(pos->member.next, type, member);      \
         &pos->member != (head);                             \
         pos = n, n = list_entry(n->member.next, type, member))
list_for_each_entry_safe - iterate over list of given type safe against removal of list entry
Parameters:
type the type of the struct where the listhead is embedded in
pos the type * to use as a loop counter.
n another type * to use as temporary storage
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 295 of file list.h.
#define list_for_each_prev (pos, head) for (pos = (head)->prev; pos != (head); pos = pos->prev)
list_for_each_prev - iterate over a list backwards
Parameters:
pos the &struct list_head to use as a loop counter.
head the head for your list.
Definition at line 249 of file list.h.
#define list_for_each_safe (pos, n, head)
Value:
for (pos = (head)->next, n = pos->next; pos != (head); \
        pos = n, n = pos->next)
list_for_each_safe - iterate over a list safe against removal of list entry
Parameters:
pos the &struct list_head to use as a loop counter.
n another &struct list_head to use as temporary storage
head the head for your list.
Definition at line 258 of file list.h.
#define LIST_HEAD (name) struct list_head name = LIST_HEAD_INIT(name)
Defines a (static) list reference.
Definition at line 33 of file list.h.
#define LIST_HEAD_INIT (name) { &(name), &(name) }
Static initializer for a list header.
Definition at line 30 of file list.h.
Typedef Documentation
typedef struct list_head list_head
List Header.
Put this into all list elements and at the place where you want to keep references to the list.
Definition at line 27 of file list.h.
Function Documentation
static void __list_add (struct list_head * new_node, struct list_head * prev, struct list_head * next) [inline, static]
Inserts a new entry between two known consecutive entries.
This is only for internal list manipulation where we know the prev/next entries already!
Definition at line 59 of file list.h.
Referenced by list_add(), and list_add_tail().
static void __list_del (struct list_head * prev, struct list_head * next) [inline, static]
Deletes a list entry by making the prev/next entries point to each other.
This is only for internal list manipulation where we know the prev/next entries already!
Definition at line 102 of file list.h.
Referenced by list_del(), list_del_init(), list_move(), and list_move_tail().
static void __list_splice (struct list_head * list, struct list_head * head) [inline, static]
Join two nonempty lists.
Note:
Use list_splice() if list is possibly empty.
Parameters:
list the new list to add.
head the place to add it in the first list.
Definition at line 173 of file list.h.
Referenced by list_splice(), and list_splice_init().
static void list_add (struct list_head * new_node, struct list_head * head) [inline, static]
Adds a new entry.
Parameters:
new_node new entry to be added
head list head to add it after
Insert a new entry after the specified head. This is good for implementing stacks.
Definition at line 77 of file list.h.
References __list_add().
Referenced by list_move().
static void list_add_tail (struct list_head * new_node, struct list_head * head) [inline, static]
Adds a new entry.
Parameters:
new_node new entry to be added
head list head to add it before
Insert a new entry before the specified head. This is useful for implementing queues.
Definition at line 90 of file list.h.
References __list_add().
Referenced by list_move_tail().
static void list_del (struct list_head * entry) [inline, static]
Deletes entry from list.
Parameters:
entry the element to delete from the list.
Note:
list_empty on entry does not return true after this, the entry is in an undefined state.
Definition at line 116 of file list.h.
References __list_del().
static void list_del_init (struct list_head * entry) [inline, static]
Deletes entry from list and reinitialize it.
Parameters:
entry the element to delete from the list.
Definition at line 128 of file list.h.
References __list_del(), and INIT_LIST_HEAD.
static int list_empty (const struct list_head * head) [inline, static]
Tests whether a list is empty.
Parameters:
head the list to test.
Definition at line 161 of file list.h.
Referenced by list_splice(), and list_splice_init().
static void list_move (struct list_head * list, struct list_head * head) [inline, static]
Deletes from one list and add as another's head.
Parameters:
list the entry to move
head the head that will precede our entry
Definition at line 139 of file list.h.
References __list_del(), and list_add().
static void list_move_tail (struct list_head * list, struct list_head * head) [inline, static]
Deletes from one list and add as another's tail.
Parameters:
list the entry to move
head the head that will follow our entry
Definition at line 150 of file list.h.
References __list_del(), and list_add_tail().
static void list_splice (struct list_head * list, struct list_head * head) [inline, static]
list_splice - join two lists
Parameters:
list the new list to add.
head the place to add it in the first list.
Definition at line 192 of file list.h.
References __list_splice(), and list_empty().
static void list_splice_init (struct list_head * list, struct list_head * head) [inline, static]
list_splice_init - join two lists and reinitialize the emptied list.
Parameters:
list the new list to add.
head the place to add it in the first list.
The list at list is reinitialized
Definition at line 205 of file list.h.
References __list_splice(), INIT_LIST_HEAD, and list_empty().