libFirm: Minus node
Minus node
Procedure Graph » Nodes
Enumerations
enum n_Minus { n_Minus_op , n_Minus_max = n_Minus_op }
Input numbers for Minus node.
Functions
ir_node * new_rd_Minus (dbg_info *dbgi, ir_node *block, ir_node *irn_op)
Construct a Minus node.
ir_node * new_r_Minus (ir_node *block, ir_node *irn_op)
Construct a Minus node.
ir_node * new_d_Minus (dbg_info *dbgi, ir_node *irn_op)
Construct a Minus node.
ir_node * new_Minus (ir_node *irn_op)
Construct a Minus node.
int is_Minus (const ir_node *node)
Test if node is a Minus.
ir_node * get_Minus_op (const ir_node *node)
Returns op input of a Minus node.
void set_Minus_op (ir_node *node, ir_node *op)
Sets op input of a Minus node.
ir_op * get_op_Minus (void)
Returns opcode for Minus nodes.
Variables
ir_op * op_Minus
Minus opcode.
Detailed Description
returns the additive inverse of its operand
Enumeration Type Documentation
n_Minus
enum n_Minus
Input numbers for Minus node.
Enumerator
n_Minus_op
operand
n_Minus_max
Definition at line 2344 of file nodes.h.
Function Documentation
get_Minus_op()
ir_node * get_Minus_op (const ir_node * node)
Returns op input of a Minus node.
Definition at line 1585 of file gen_irnode.c.
get_op_Minus()
ir_op * get_op_Minus (void)
Returns opcode for Minus nodes.
Definition at line 1595 of file gen_irnode.c.
References op_Minus.
is_Minus()
int is_Minus (const ir_node * node)
Test if node is a Minus.
Returns
1 if the node is a Minus node, 0 otherwise
Definition at line 3322 of file gen_irnode.c.
new_d_Minus()
ir_node * new_d_Minus (dbg_info * dbgi, ir_node * irn_op)
Construct a Minus node.
Parameters
dbgi A pointer to debug information.
irn_op op
Definition at line 1573 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Minus().
Referenced by new_Minus().
new_Minus()
ir_node * new_Minus (ir_node * irn_op)
Construct a Minus node.
Parameters
irn_op op
Definition at line 1580 of file gen_irnode.c.
References new_d_Minus().
new_r_Minus()
ir_node * new_r_Minus (ir_node * block, ir_node * irn_op)
Construct a Minus node.
Parameters
block The IR block the node belongs to.
irn_op op
Definition at line 1568 of file gen_irnode.c.
References new_rd_Minus().
new_rd_Minus()
ir_node * new_rd_Minus (dbg_info * dbgi, ir_node * block, ir_node * irn_op)
Construct a Minus node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
Definition at line 1553 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Minus, optimize_node(), and verify_new_node().
Referenced by new_d_Minus(), and new_r_Minus().
set_Minus_op()
void set_Minus_op (ir_node * node, ir_node * op)
Sets op input of a Minus node.
Definition at line 1590 of file gen_irnode.c.
Variable Documentation
op_Minus
ir_op* op_Minus
Minus opcode.
Definition at line 2392 of file nodes.h.
Referenced by get_op_Minus(), and new_rd_Minus().