libFirm: End node
End node
Procedure Graph » Nodes
Functions
void add_End_keepalive (ir_node *end, ir_node *ka)
Keep alive dedicated nodes.
void set_End_keepalives (ir_node *end, int n, ir_node *in[])
Sets new keep-alives.
void remove_End_keepalive (ir_node *end, const ir_node *irn)
Removes irn from the keep-alive set.
void remove_End_n (ir_node *end, int idx)
Removes predecessor (a keepalive) at index idx from End node end.
void remove_End_Bads_and_doublets (ir_node *end)
Removes Bads, NoMem and doublets from the keep-alive set.
void free_End (ir_node *end)
Some parts of the End node are allocated separately – their memory is not recovered by dead_node_elimination if a End node is dead.
ir_node * new_rd_End (dbg_info *dbgi, ir_graph *irg, int arity, ir_node *const *in)
Construct an End node.
ir_node * new_r_End (ir_graph *irg, int arity, ir_node *const *in)
Construct an End node.
ir_node * new_d_End (dbg_info *dbgi, int arity, ir_node *const *in)
Construct an End node.
ir_node * new_End (int arity, ir_node *const *in)
Construct an End node.
int is_End (const ir_node *node)
Test if node is a End.
int get_End_n_keepalives (ir_node const *node)
Get the number of End keepalives.
ir_node * get_End_keepalive (ir_node const *node, int pos)
Get the End keepalive with index pos.
void set_End_keepalive (ir_node *node, int pos, ir_node *keepalive)
Set the End keepalive with index pos.
ir_node ** get_End_keepalive_arr (ir_node *node)
Get an array of all End keepalives.
ir_op * get_op_End (void)
Returns opcode for End nodes.
Variables
ir_op * op_End
End opcode.
Detailed Description
Last node of a graph. It references nodes in endless loops (so called keepalive edges)
Function Documentation
add_End_keepalive()
void add_End_keepalive (ir_node * end, ir_node * ka)
Keep alive dedicated nodes.
These must be either PhiM or Block nodes.
free_End()
void free_End (ir_node * end)
Some parts of the End node are allocated separately – their memory is not recovered by dead_node_elimination if a End node is dead.
free_End() frees these data structures.
get_End_keepalive()
ir_node * get_End_keepalive (ir_node const * node, int pos)
Get the End keepalive with index pos.
Definition at line 1207 of file gen_irnode.c.
get_End_keepalive_arr()
ir_node ** get_End_keepalive_arr (ir_node * node)
Get an array of all End keepalives.
Definition at line 1217 of file gen_irnode.c.
get_End_n_keepalives()
int get_End_n_keepalives (ir_node const * node)
Get the number of End keepalives.
Definition at line 1202 of file gen_irnode.c.
get_op_End()
ir_op * get_op_End (void)
Returns opcode for End nodes.
Definition at line 1222 of file gen_irnode.c.
References op_End.
is_End()
int is_End (const ir_node * node)
Test if node is a End.
Returns
1 if the node is a End node, 0 otherwise
Definition at line 3232 of file gen_irnode.c.
new_d_End()
ir_node * new_d_End (dbg_info * dbgi, int arity, ir_node *const * in)
Construct an End node.
Parameters
dbgi A pointer to debug information.
arity size of additional inputs array
in additional inputs
Definition at line 1190 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_End().
Referenced by new_End().
new_End()
ir_node * new_End (int arity, ir_node *const * in)
Construct an End node.
Parameters
arity size of additional inputs array
in additional inputs
Definition at line 1197 of file gen_irnode.c.
References new_d_End().
new_r_End()
ir_node * new_r_End (ir_graph * irg, int arity, ir_node *const * in)
Construct an End node.
Parameters
irg The IR graph the node belongs to.
arity size of additional inputs array
in additional inputs
Definition at line 1185 of file gen_irnode.c.
References new_rd_End().
new_rd_End()
ir_node * new_rd_End (dbg_info * dbgi, ir_graph * irg, int arity, ir_node *const * in)
Construct an End node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
arity size of additional inputs array
in additional inputs
Definition at line 1172 of file gen_irnode.c.
References get_irg_end_block(), mode_X, new_ir_node(), op_End, optimize_node(), and verify_new_node().
Referenced by new_d_End(), and new_r_End().
remove_End_Bads_and_doublets()
void remove_End_Bads_and_doublets (ir_node * end)
Removes Bads, NoMem and doublets from the keep-alive set.
remove_End_keepalive()
void remove_End_keepalive (ir_node * end, const ir_node * irn)
Removes irn from the keep-alive set.
remove_End_n()
void remove_End_n (ir_node * end, int idx)
Removes predecessor (a keepalive) at index idx from End node end.
set_End_keepalive()
void set_End_keepalive (ir_node * node, int pos, ir_node * keepalive)
Set the End keepalive with index pos.
Definition at line 1212 of file gen_irnode.c.
set_End_keepalives()
void set_End_keepalives (ir_node * end, int n, ir_node * in[])
Sets new keep-alives.
Beware: This might be an expensive operation if dynamic edges are enabled, so avoid it in the backend.
Variable Documentation
op_End
ir_op* op_End
End opcode.
Definition at line 1830 of file nodes.h.
Referenced by get_op_End(), and new_rd_End().