libFirm: Address node
Address node
Procedure Graph » Nodes
Functions
ir_node * new_rd_Address (dbg_info *dbgi, ir_graph *irg, ir_entity *entity)
Construct an Address node.
ir_node * new_r_Address (ir_graph *irg, ir_entity *entity)
Construct an Address node.
ir_node * new_d_Address (dbg_info *dbgi, ir_entity *entity)
Construct an Address node.
ir_node * new_Address (ir_entity *entity)
Construct an Address node.
int is_Address (const ir_node *node)
Test if node is a Address.
ir_entity * get_Address_entity (const ir_node *node)
Returns entity attribute of an Address node.
void set_Address_entity (ir_node *node, ir_entity *entity)
Sets entity attribute of an Address node.
ir_op * get_op_Address (void)
Returns opcode for Address nodes.
Variables
ir_op * op_Address
Address opcode.
Detailed Description
Symbolic constant that represents the address of an entity (variable or method)
Function Documentation
get_Address_entity()
ir_entity * get_Address_entity (const ir_node * node)
Returns entity attribute of an Address node.
Definition at line 2992 of file gen_irnode.c.
get_op_Address()
ir_op * get_op_Address (void)
Returns opcode for Address nodes.
Definition at line 189 of file gen_irnode.c.
References op_Address.
is_Address()
int is_Address (const ir_node * node)
Test if node is a Address.
Returns
1 if the node is a Address node, 0 otherwise
Definition at line 2987 of file gen_irnode.c.
new_Address()
ir_node * new_Address (ir_entity * entity)
Construct an Address node.
Parameters
entity entity to operate on
Definition at line 184 of file gen_irnode.c.
References new_d_Address().
new_d_Address()
ir_node * new_d_Address (dbg_info * dbgi, ir_entity * entity)
Construct an Address node.
Parameters
dbgi A pointer to debug information.
entity entity to operate on
Definition at line 177 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Address().
Referenced by new_Address().
new_r_Address()
ir_node * new_r_Address (ir_graph * irg, ir_entity * entity)
Construct an Address node.
Parameters
irg The IR graph the node belongs to.
entity entity to operate on
Definition at line 172 of file gen_irnode.c.
References new_rd_Address().
new_rd_Address()
ir_node * new_rd_Address (dbg_info * dbgi, ir_graph * irg, ir_entity * entity)
Construct an Address node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
entity entity to operate on
Definition at line 158 of file gen_irnode.c.
References get_irg_start_block(), mode_P, new_ir_node(), op_Address, optimize_node(), and verify_new_node().
Referenced by new_d_Address(), and new_r_Address().
set_Address_entity()
void set_Address_entity (ir_node * node, ir_entity * entity)
Sets entity attribute of an Address node.
Definition at line 2997 of file gen_irnode.c.
Variable Documentation
op_Address
ir_op* op_Address
Address opcode.
Definition at line 362 of file nodes.h.
Referenced by get_op_Address(), and new_rd_Address().