libFirm: Conv node
Conv node
Procedure Graph » Nodes
Enumerations
enum n_Conv { n_Conv_op , n_Conv_max = n_Conv_op }
Input numbers for Conv node.
Functions
ir_node * new_rd_Conv (dbg_info *dbgi, ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_r_Conv (ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_d_Conv (dbg_info *dbgi, ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
ir_node * new_Conv (ir_node *irn_op, ir_mode *mode)
Construct a Conv node.
int is_Conv (const ir_node *node)
Test if node is a Conv.
ir_node * get_Conv_op (const ir_node *node)
Returns op input of a Conv node.
void set_Conv_op (ir_node *node, ir_node *op)
Sets op input of a Conv node.
ir_op * get_op_Conv (void)
Returns opcode for Conv nodes.
Variables
ir_op * op_Conv
Conv opcode.
Detailed Description
Converts values between modes
Enumeration Type Documentation
n_Conv
enum n_Conv
Input numbers for Conv node.
Enumerator
n_Conv_op
operand
n_Conv_max
Definition at line 1425 of file nodes.h.
Function Documentation
get_Conv_op()
ir_node * get_Conv_op (const ir_node * node)
Returns op input of a Conv node.
Definition at line 973 of file gen_irnode.c.
get_op_Conv()
ir_op * get_op_Conv (void)
Returns opcode for Conv nodes.
Definition at line 983 of file gen_irnode.c.
References op_Conv.
is_Conv()
int is_Conv (const ir_node * node)
Test if node is a Conv.
Returns
1 if the node is a Conv node, 0 otherwise
Definition at line 3167 of file gen_irnode.c.
new_Conv()
ir_node * new_Conv (ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
irn_op op
mode mode of the operations result
Definition at line 968 of file gen_irnode.c.
References new_d_Conv().
new_d_Conv()
ir_node * new_d_Conv (dbg_info * dbgi, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
dbgi A pointer to debug information.
irn_op op
mode mode of the operations result
Definition at line 961 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Conv().
Referenced by new_Conv().
new_r_Conv()
ir_node * new_r_Conv (ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 956 of file gen_irnode.c.
References new_rd_Conv().
new_rd_Conv()
ir_node * new_rd_Conv (dbg_info * dbgi, ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Conv node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 941 of file gen_irnode.c.
References get_irn_irg(), new_ir_node(), op_Conv, optimize_node(), and verify_new_node().
Referenced by new_d_Conv(), and new_r_Conv().
set_Conv_op()
void set_Conv_op (ir_node * node, ir_node * op)
Sets op input of a Conv node.
Definition at line 978 of file gen_irnode.c.
Variable Documentation
op_Conv
ir_op* op_Conv
Conv opcode.
Definition at line 1477 of file nodes.h.
Referenced by get_op_Conv(), and new_rd_Conv().