libFirm: IJmp node
IJmp node
Procedure Graph » Nodes
Enumerations
enum n_IJmp { n_IJmp_target , n_IJmp_max = n_IJmp_target }
Input numbers for IJmp node.
Functions
ir_node * new_rd_IJmp (dbg_info *dbgi, ir_node *block, ir_node *irn_target)
Construct an IJmp node.
ir_node * new_r_IJmp (ir_node *block, ir_node *irn_target)
Construct an IJmp node.
ir_node * new_d_IJmp (dbg_info *dbgi, ir_node *irn_target)
Construct an IJmp node.
ir_node * new_IJmp (ir_node *irn_target)
Construct an IJmp node.
int is_IJmp (const ir_node *node)
Test if node is a IJmp.
ir_node * get_IJmp_target (const ir_node *node)
Returns target input of an IJmp node.
void set_IJmp_target (ir_node *node, ir_node *target)
Sets target input of an IJmp node.
ir_op * get_op_IJmp (void)
Returns opcode for IJmp nodes.
Variables
ir_op * op_IJmp
IJmp opcode.
Detailed Description
Jumps to the code in its argument. The code has to be in the same function and the destination must be one of the blocks reachable by the tuple results
Enumeration Type Documentation
n_IJmp
enum n_IJmp
Input numbers for IJmp node.
Enumerator
n_IJmp_target
target address of the jump
n_IJmp_max
Definition at line 1999 of file nodes.h.
Function Documentation
get_IJmp_target()
ir_node * get_IJmp_target (const ir_node * node)
Returns target input of an IJmp node.
Definition at line 1375 of file gen_irnode.c.
get_op_IJmp()
ir_op * get_op_IJmp (void)
Returns opcode for IJmp nodes.
Definition at line 1385 of file gen_irnode.c.
References op_IJmp.
is_IJmp()
int is_IJmp (const ir_node * node)
Test if node is a IJmp.
Returns
1 if the node is a IJmp node, 0 otherwise
Definition at line 3247 of file gen_irnode.c.
new_d_IJmp()
ir_node * new_d_IJmp (dbg_info * dbgi, ir_node * irn_target)
Construct an IJmp node.
Parameters
dbgi A pointer to debug information.
irn_target target
Definition at line 1363 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_IJmp().
Referenced by new_IJmp().
new_IJmp()
ir_node * new_IJmp (ir_node * irn_target)
Construct an IJmp node.
Parameters
irn_target target
Definition at line 1370 of file gen_irnode.c.
References new_d_IJmp().
new_r_IJmp()
ir_node * new_r_IJmp (ir_node * block, ir_node * irn_target)
Construct an IJmp node.
Parameters
block The IR block the node belongs to.
irn_target target
Definition at line 1358 of file gen_irnode.c.
References new_rd_IJmp().
new_rd_IJmp()
ir_node * new_rd_IJmp (dbg_info * dbgi, ir_node * block, ir_node * irn_target)
Construct an IJmp node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_target target
Definition at line 1343 of file gen_irnode.c.
References get_irn_irg(), mode_X, new_ir_node(), op_IJmp, optimize_node(), and verify_new_node().
Referenced by new_d_IJmp(), and new_r_IJmp().
set_IJmp_target()
void set_IJmp_target (ir_node * node, ir_node * target)
Sets target input of an IJmp node.
Definition at line 1380 of file gen_irnode.c.
Variable Documentation
op_IJmp
ir_op* op_IJmp
IJmp opcode.
Definition at line 2047 of file nodes.h.
Referenced by get_op_IJmp(), and new_rd_IJmp().