libFirm: Mul node
Mul node
Procedure Graph » Nodes
Enumerations
enum n_Mul { n_Mul_left , n_Mul_right , n_Mul_max = n_Mul_right }
Input numbers for Mul node.
Functions
ir_node * new_rd_Mul (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Mul node.
ir_node * new_r_Mul (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Mul node.
ir_node * new_d_Mul (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct a Mul node.
ir_node * new_Mul (ir_node *irn_left, ir_node *irn_right)
Construct a Mul node.
int is_Mul (const ir_node *node)
Test if node is a Mul.
ir_node * get_Mul_left (const ir_node *node)
Returns left input of a Mul node.
void set_Mul_left (ir_node *node, ir_node *left)
Sets left input of a Mul node.
ir_node * get_Mul_right (const ir_node *node)
Returns right input of a Mul node.
void set_Mul_right (ir_node *node, ir_node *right)
Sets right input of a Mul node.
ir_op * get_op_Mul (void)
Returns opcode for Mul nodes.
Variables
ir_op * op_Mul
Mul opcode.
Detailed Description
returns the product of its operands
Enumeration Type Documentation
n_Mul
enum n_Mul
Input numbers for Mul node.
Enumerator
n_Mul_left
first operand
n_Mul_right
second operand
n_Mul_max
Definition at line 2519 of file nodes.h.
Function Documentation
get_Mul_left()
ir_node * get_Mul_left (const ir_node * node)
Returns left input of a Mul node.
Definition at line 1705 of file gen_irnode.c.
get_Mul_right()
ir_node * get_Mul_right (const ir_node * node)
Returns right input of a Mul node.
Definition at line 1715 of file gen_irnode.c.
get_op_Mul()
ir_op * get_op_Mul (void)
Returns opcode for Mul nodes.
Definition at line 1725 of file gen_irnode.c.
References op_Mul.
is_Mul()
int is_Mul (const ir_node * node)
Test if node is a Mul.
Returns
1 if the node is a Mul node, 0 otherwise
Definition at line 3342 of file gen_irnode.c.
new_d_Mul()
ir_node * new_d_Mul (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct a Mul node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 1693 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Mul().
Referenced by new_Mul().
new_Mul()
ir_node * new_Mul (ir_node * irn_left, ir_node * irn_right)
Construct a Mul node.
Parameters
irn_left left
irn_right right
Definition at line 1700 of file gen_irnode.c.
References new_d_Mul().
new_r_Mul()
ir_node * new_r_Mul (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Mul node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1688 of file gen_irnode.c.
References new_rd_Mul().
new_rd_Mul()
ir_node * new_rd_Mul (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Mul node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1672 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Mul, optimize_node(), and verify_new_node().
Referenced by new_d_Mul(), and new_r_Mul().
set_Mul_left()
void set_Mul_left (ir_node * node, ir_node * left)
Sets left input of a Mul node.
Definition at line 1710 of file gen_irnode.c.
set_Mul_right()
void set_Mul_right (ir_node * node, ir_node * right)
Sets right input of a Mul node.
Definition at line 1720 of file gen_irnode.c.
Variable Documentation
op_Mul
ir_op* op_Mul
Mul opcode.
Definition at line 2576 of file nodes.h.
Referenced by get_op_Mul(), and new_rd_Mul().