libFirm: Return node
Return node
Procedure Graph » Nodes
Enumerations
enum n_Return { n_Return_mem , n_Return_max = n_Return_mem }
Input numbers for Return node.
Functions
ir_node * new_rd_Return (dbg_info *dbgi, ir_node *block, ir_node *irn_mem, int arity, ir_node *const *in)
Construct a Return node.
ir_node * new_r_Return (ir_node *block, ir_node *irn_mem, int arity, ir_node *const *in)
Construct a Return node.
ir_node * new_d_Return (dbg_info *dbgi, ir_node *irn_mem, int arity, ir_node *const *in)
Construct a Return node.
ir_node * new_Return (ir_node *irn_mem, int arity, ir_node *const *in)
Construct a Return node.
int is_Return (const ir_node *node)
Test if node is a Return.
ir_node * get_Return_mem (const ir_node *node)
Returns mem input of a Return node.
void set_Return_mem (ir_node *node, ir_node *mem)
Sets mem input of a Return node.
int get_Return_n_ress (ir_node const *node)
Get the number of Return ress.
ir_node * get_Return_res (ir_node const *node, int pos)
Get the Return res with index pos.
void set_Return_res (ir_node *node, int pos, ir_node *res)
Set the Return res with index pos.
ir_node ** get_Return_res_arr (ir_node *node)
Get an array of all Return ress.
ir_op * get_op_Return (void)
Returns opcode for Return nodes.
Variables
ir_op * op_Return
Return opcode.
Detailed Description
Returns from the current function. Takes memory and return values as operands.
Enumeration Type Documentation
n_Return
enum n_Return
Input numbers for Return node.
Enumerator
n_Return_mem
memory dependency
n_Return_max
Definition at line 3307 of file nodes.h.
Function Documentation
get_op_Return()
ir_op * get_op_Return (void)
Returns opcode for Return nodes.
Definition at line 2309 of file gen_irnode.c.
References op_Return.
get_Return_mem()
ir_node * get_Return_mem (const ir_node * node)
Returns mem input of a Return node.
Definition at line 2279 of file gen_irnode.c.
get_Return_n_ress()
int get_Return_n_ress (ir_node const * node)
Get the number of Return ress.
Definition at line 2289 of file gen_irnode.c.
get_Return_res()
ir_node * get_Return_res (ir_node const * node, int pos)
Get the Return res with index pos.
Definition at line 2294 of file gen_irnode.c.
get_Return_res_arr()
ir_node ** get_Return_res_arr (ir_node * node)
Get an array of all Return ress.
Definition at line 2304 of file gen_irnode.c.
is_Return()
int is_Return (const ir_node * node)
Test if node is a Return.
Returns
1 if the node is a Return node, 0 otherwise
Definition at line 3427 of file gen_irnode.c.
new_d_Return()
ir_node * new_d_Return (dbg_info * dbgi, ir_node * irn_mem, int arity, ir_node *const * in)
Construct a Return node.
Parameters
dbgi A pointer to debug information.
irn_mem mem
arity size of additional inputs array
in additional inputs
Definition at line 2267 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Return().
Referenced by new_Return().
new_r_Return()
ir_node * new_r_Return (ir_node * block, ir_node * irn_mem, int arity, ir_node *const * in)
Construct a Return node.
Parameters
block The IR block the node belongs to.
irn_mem mem
arity size of additional inputs array
in additional inputs
Definition at line 2262 of file gen_irnode.c.
References new_rd_Return().
new_rd_Return()
ir_node * new_rd_Return (dbg_info * dbgi, ir_node * block, ir_node * irn_mem, int arity, ir_node *const * in)
Construct a Return node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_mem mem
arity size of additional inputs array
in additional inputs
Definition at line 2244 of file gen_irnode.c.
References ALLOCAN, get_irn_irg(), mode_X, new_ir_node(), op_Return, optimize_node(), and verify_new_node().
Referenced by new_d_Return(), and new_r_Return().
new_Return()
ir_node * new_Return (ir_node * irn_mem, int arity, ir_node *const * in)
Construct a Return node.
Parameters
irn_mem mem
arity size of additional inputs array
in additional inputs
Definition at line 2274 of file gen_irnode.c.
References new_d_Return().
set_Return_mem()
void set_Return_mem (ir_node * node, ir_node * mem)
Sets mem input of a Return node.
Definition at line 2284 of file gen_irnode.c.
set_Return_res()
void set_Return_res (ir_node * node, int pos, ir_node * res)
Set the Return res with index pos.
Definition at line 2299 of file gen_irnode.c.
Variable Documentation
op_Return
ir_op* op_Return
Return opcode.
Definition at line 3371 of file nodes.h.
Referenced by get_op_Return(), and new_rd_Return().