libFirm: Jmp node
Jmp node
Procedure Graph » Nodes
Functions
ir_node * new_rd_Jmp (dbg_info *dbgi, ir_node *block)
Construct a Jmp node.
ir_node * new_r_Jmp (ir_node *block)
Construct a Jmp node.
ir_node * new_d_Jmp (dbg_info *dbgi)
Construct a Jmp node.
ir_node * new_Jmp (void)
Construct a Jmp node.
int is_Jmp (const ir_node *node)
Test if node is a Jmp.
ir_op * get_op_Jmp (void)
Returns opcode for Jmp nodes.
Variables
ir_op * op_Jmp
Jmp opcode.
Detailed Description
Jumps to the block connected through the out-value
Function Documentation
get_op_Jmp()
ir_op * get_op_Jmp (void)
Returns opcode for Jmp nodes.
Definition at line 1436 of file gen_irnode.c.
References op_Jmp.
is_Jmp()
int is_Jmp (const ir_node * node)
Test if node is a Jmp.
Returns
1 if the node is a Jmp node, 0 otherwise
Definition at line 3257 of file gen_irnode.c.
new_d_Jmp()
ir_node * new_d_Jmp (dbg_info * dbgi)
Construct a Jmp node.
Parameters
dbgi A pointer to debug information.
Definition at line 1424 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Jmp().
Referenced by new_Jmp().
new_Jmp()
ir_node * new_Jmp (void)
Construct a Jmp node.
Definition at line 1431 of file gen_irnode.c.
References new_d_Jmp().
new_r_Jmp()
ir_node * new_r_Jmp (ir_node * block)
Construct a Jmp node.
Parameters
block The IR block the node belongs to.
Definition at line 1419 of file gen_irnode.c.
References new_rd_Jmp().
new_rd_Jmp()
ir_node * new_rd_Jmp (dbg_info * dbgi, ir_node * block)
Construct a Jmp node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
Definition at line 1405 of file gen_irnode.c.
References get_irn_irg(), mode_X, new_ir_node(), op_Jmp, optimize_node(), and verify_new_node().
Referenced by new_d_Jmp(), and new_r_Jmp().
Variable Documentation
op_Jmp
ir_op* op_Jmp
Jmp opcode.
Definition at line 2133 of file nodes.h.
Referenced by get_op_Jmp(), and new_rd_Jmp().