libFirm: Start node
Start node
Procedure Graph » Nodes
Enumerations
enum pn_Start { pn_Start_M , pn_Start_P_frame_base , pn_Start_T_args , pn_Start_max = pn_Start_T_args }
Projection numbers for result of Start node (use for Proj nodes)
Functions
ir_node * new_rd_Start (dbg_info *dbgi, ir_graph *irg)
Construct a Start node.
ir_node * new_r_Start (ir_graph *irg)
Construct a Start node.
ir_node * new_d_Start (dbg_info *dbgi)
Construct a Start node.
ir_node * new_Start (void)
Construct a Start node.
int is_Start (const ir_node *node)
Test if node is a Start.
ir_op * get_op_Start (void)
Returns opcode for Start nodes.
Variables
ir_op * op_Start
Start opcode.
Detailed Description
The first node of a graph. Execution starts with this node.
Enumeration Type Documentation
pn_Start
enum pn_Start
Projection numbers for result of Start node (use for Proj nodes)
Enumerator
pn_Start_M
initial memory
pn_Start_P_frame_base
frame base pointer
pn_Start_T_args
function arguments
pn_Start_max
Definition at line 3771 of file nodes.h.
Function Documentation
get_op_Start()
ir_op * get_op_Start (void)
Returns opcode for Start nodes.
Definition at line 2613 of file gen_irnode.c.
References op_Start.
is_Start()
int is_Start (const ir_node * node)
Test if node is a Start.
Returns
1 if the node is a Start node, 0 otherwise
Definition at line 3477 of file gen_irnode.c.
new_d_Start()
ir_node * new_d_Start (dbg_info * dbgi)
Construct a Start node.
Parameters
dbgi A pointer to debug information.
Definition at line 2601 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Start().
Referenced by new_Start().
new_r_Start()
ir_node * new_r_Start (ir_graph * irg)
Construct a Start node.
Parameters
irg The IR graph the node belongs to.
Definition at line 2596 of file gen_irnode.c.
References new_rd_Start().
new_rd_Start()
ir_node * new_rd_Start (dbg_info * dbgi, ir_graph * irg)
Construct a Start node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
Definition at line 2583 of file gen_irnode.c.
References get_irg_start_block(), mode_T, new_ir_node(), op_Start, optimize_node(), and verify_new_node().
Referenced by new_d_Start(), and new_r_Start().
new_Start()
ir_node * new_Start (void)
Construct a Start node.
Definition at line 2608 of file gen_irnode.c.
References new_d_Start().
Variable Documentation
op_Start
ir_op* op_Start
Start opcode.
Definition at line 3813 of file nodes.h.
Referenced by get_op_Start(), and new_rd_Start().