libFirm: Unknown node
Unknown node
Procedure Graph » Nodes
Functions
ir_node * new_rd_Unknown (dbg_info *dbgi, ir_graph *irg, ir_mode *mode)
Construct an Unknown node.
ir_node * new_r_Unknown (ir_graph *irg, ir_mode *mode)
Construct an Unknown node.
ir_node * new_d_Unknown (dbg_info *dbgi, ir_mode *mode)
Construct an Unknown node.
ir_node * new_Unknown (ir_mode *mode)
Construct an Unknown node.
int is_Unknown (const ir_node *node)
Test if node is a Unknown.
ir_op * get_op_Unknown (void)
Returns opcode for Unknown nodes.
Variables
ir_op * op_Unknown
Unknown opcode.
Detailed Description
Returns an unknown (at compile- and runtime) value. It is a valid optimization to replace an Unknown by any other constant value.
Be careful when optimising Unknown values, you cannot simply replace Unknown+x or Unknown<x with a new Unknown node if there are multiple users of the original unknown node!
Function Documentation
get_op_Unknown()
ir_op * get_op_Unknown (void)
Returns opcode for Unknown nodes.
Definition at line 2941 of file gen_irnode.c.
References op_Unknown.
is_Unknown()
int is_Unknown (const ir_node * node)
Test if node is a Unknown.
Returns
1 if the node is a Unknown node, 0 otherwise
Definition at line 3557 of file gen_irnode.c.
new_d_Unknown()
ir_node * new_d_Unknown (dbg_info * dbgi, ir_mode * mode)
Construct an Unknown node.
Parameters
dbgi A pointer to debug information.
mode mode of the operations result
Definition at line 2929 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Unknown().
Referenced by new_Unknown().
new_r_Unknown()
ir_node * new_r_Unknown (ir_graph * irg, ir_mode * mode)
Construct an Unknown node.
Parameters
irg The IR graph the node belongs to.
mode mode of the operations result
Definition at line 2924 of file gen_irnode.c.
References new_rd_Unknown().
new_rd_Unknown()
ir_node * new_rd_Unknown (dbg_info * dbgi, ir_graph * irg, ir_mode * mode)
Construct an Unknown node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
mode mode of the operations result
Definition at line 2911 of file gen_irnode.c.
References get_irg_start_block(), new_ir_node(), op_Unknown, optimize_node(), and verify_new_node().
Referenced by new_d_Unknown(), and new_r_Unknown().
new_Unknown()
ir_node * new_Unknown (ir_mode * mode)
Construct an Unknown node.
Parameters
mode mode of the operations result
Definition at line 2936 of file gen_irnode.c.
References new_d_Unknown().
Variable Documentation
op_Unknown
ir_op* op_Unknown
Unknown opcode.
Definition at line 4296 of file nodes.h.
Referenced by get_op_Unknown(), and new_rd_Unknown().