libFirm: Bitcast node
Bitcast node
Procedure Graph » Nodes
Enumerations
enum n_Bitcast { n_Bitcast_op , n_Bitcast_max = n_Bitcast_op }
Input numbers for Bitcast node.
Functions
ir_node * new_rd_Bitcast (dbg_info *dbgi, ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_r_Bitcast (ir_node *block, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_d_Bitcast (dbg_info *dbgi, ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
ir_node * new_Bitcast (ir_node *irn_op, ir_mode *mode)
Construct a Bitcast node.
int is_Bitcast (const ir_node *node)
Test if node is a Bitcast.
ir_node * get_Bitcast_op (const ir_node *node)
Returns op input of a Bitcast node.
void set_Bitcast_op (ir_node *node, ir_node *op)
Sets op input of a Bitcast node.
ir_op * get_op_Bitcast (void)
Returns opcode for Bitcast nodes.
Variables
ir_op * op_Bitcast
Bitcast opcode.
Detailed Description
Converts a value between modes with different arithmetics but same number of bits by reinterpreting the bits in the new mode
Enumeration Type Documentation
n_Bitcast
enum n_Bitcast
Input numbers for Bitcast node.
Enumerator
n_Bitcast_op
operand
n_Bitcast_max
Definition at line 754 of file nodes.h.
Function Documentation
get_Bitcast_op()
ir_node * get_Bitcast_op (const ir_node * node)
Returns op input of a Bitcast node.
Definition at line 499 of file gen_irnode.c.
get_op_Bitcast()
ir_op * get_op_Bitcast (void)
Returns opcode for Bitcast nodes.
Definition at line 509 of file gen_irnode.c.
References op_Bitcast.
is_Bitcast()
int is_Bitcast (const ir_node * node)
Test if node is a Bitcast.
Returns
1 if the node is a Bitcast node, 0 otherwise
Definition at line 3047 of file gen_irnode.c.
new_Bitcast()
ir_node * new_Bitcast (ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
irn_op op
mode mode of the operations result
Definition at line 494 of file gen_irnode.c.
References new_d_Bitcast().
new_d_Bitcast()
ir_node * new_d_Bitcast (dbg_info * dbgi, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
dbgi A pointer to debug information.
irn_op op
mode mode of the operations result
Definition at line 487 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Bitcast().
Referenced by new_Bitcast().
new_r_Bitcast()
ir_node * new_r_Bitcast (ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 482 of file gen_irnode.c.
References new_rd_Bitcast().
new_rd_Bitcast()
ir_node * new_rd_Bitcast (dbg_info * dbgi, ir_node * block, ir_node * irn_op, ir_mode * mode)
Construct a Bitcast node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_op op
mode mode of the operations result
Definition at line 467 of file gen_irnode.c.
References get_irn_irg(), new_ir_node(), op_Bitcast, optimize_node(), and verify_new_node().
Referenced by new_d_Bitcast(), and new_r_Bitcast().
set_Bitcast_op()
void set_Bitcast_op (ir_node * node, ir_node * op)
Sets op input of a Bitcast node.
Definition at line 504 of file gen_irnode.c.
Variable Documentation
op_Bitcast
ir_op* op_Bitcast
Bitcast opcode.
Definition at line 806 of file nodes.h.
Referenced by get_op_Bitcast(), and new_rd_Bitcast().