libFirm: Proj node
Proj node
Procedure Graph » Nodes
Enumerations
enum n_Proj { n_Proj_pred , n_Proj_max = n_Proj_pred }
Input numbers for Proj node.
Functions
ir_node * new_rd_Proj (dbg_info *dbgi, ir_node *irn_pred, ir_mode *mode, unsigned num)
Construct a Proj node.
ir_node * new_r_Proj (ir_node *irn_pred, ir_mode *mode, unsigned num)
Construct a Proj node.
ir_node * new_d_Proj (dbg_info *dbgi, ir_node *irn_pred, ir_mode *mode, unsigned num)
Construct a Proj node.
ir_node * new_Proj (ir_node *irn_pred, ir_mode *mode, unsigned num)
Construct a Proj node.
int is_Proj (const ir_node *node)
Test if node is a Proj.
ir_node * get_Proj_pred (const ir_node *node)
Returns pred input of a Proj node.
void set_Proj_pred (ir_node *node, ir_node *pred)
Sets pred input of a Proj node.
unsigned get_Proj_num (const ir_node *node)
Returns num attribute of a Proj node.
void set_Proj_num (ir_node *node, unsigned num)
Sets num attribute of a Proj node.
ir_op * get_op_Proj (void)
Returns opcode for Proj nodes.
Variables
ir_op * op_Proj
Proj opcode.
Detailed Description
returns an entry of a tuple value
Enumeration Type Documentation
n_Proj
enum n_Proj
Input numbers for Proj node.
Enumerator
n_Proj_pred
the tuple value from which a part is extracted
n_Proj_max
Definition at line 3145 of file nodes.h.
Function Documentation
get_op_Proj()
ir_op * get_op_Proj (void)
Returns opcode for Proj nodes.
Definition at line 2181 of file gen_irnode.c.
References op_Proj.
get_Proj_num()
unsigned get_Proj_num (const ir_node * node)
Returns num attribute of a Proj node.
Definition at line 3412 of file gen_irnode.c.
get_Proj_pred()
ir_node * get_Proj_pred (const ir_node * node)
Returns pred input of a Proj node.
Definition at line 2171 of file gen_irnode.c.
is_Proj()
int is_Proj (const ir_node * node)
Test if node is a Proj.
Returns
1 if the node is a Proj node, 0 otherwise
Definition at line 3407 of file gen_irnode.c.
new_d_Proj()
ir_node * new_d_Proj (dbg_info * dbgi, ir_node * irn_pred, ir_mode * mode, unsigned num)
Construct a Proj node.
Parameters
dbgi A pointer to debug information.
irn_pred pred
mode mode of the operations result
num number of tuple component to be extracted
Definition at line 2159 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Proj().
Referenced by new_Proj().
new_Proj()
ir_node * new_Proj (ir_node * irn_pred, ir_mode * mode, unsigned num)
Construct a Proj node.
Parameters
irn_pred pred
mode mode of the operations result
num number of tuple component to be extracted
Definition at line 2166 of file gen_irnode.c.
References new_d_Proj().
new_r_Proj()
ir_node * new_r_Proj (ir_node * irn_pred, ir_mode * mode, unsigned num)
Construct a Proj node.
Parameters
irn_pred pred
mode mode of the operations result
num number of tuple component to be extracted
Definition at line 2154 of file gen_irnode.c.
References new_rd_Proj().
new_rd_Proj()
ir_node * new_rd_Proj (dbg_info * dbgi, ir_node * irn_pred, ir_mode * mode, unsigned num)
Construct a Proj node.
Parameters
dbgi A pointer to debug information.
irn_pred pred
mode mode of the operations result
num number of tuple component to be extracted
Definition at line 2138 of file gen_irnode.c.
References get_irn_irg(), get_nodes_block(), new_ir_node(), op_Proj, optimize_node(), and verify_new_node().
Referenced by new_d_Proj(), and new_r_Proj().
set_Proj_num()
void set_Proj_num (ir_node * node, unsigned num)
Sets num attribute of a Proj node.
Definition at line 3417 of file gen_irnode.c.
set_Proj_pred()
void set_Proj_pred (ir_node * node, ir_node * pred)
Sets pred input of a Proj node.
Definition at line 2176 of file gen_irnode.c.
Variable Documentation
op_Proj
ir_op* op_Proj
Proj opcode.
Definition at line 3204 of file nodes.h.
Referenced by get_op_Proj(), and new_rd_Proj().