libFirm: Sub node
Sub node
Procedure Graph » Nodes
Enumerations
enum n_Sub { n_Sub_left , n_Sub_right , n_Sub_max = n_Sub_right }
Input numbers for Sub node.
Functions
ir_node * new_rd_Sub (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Sub node.
ir_node * new_r_Sub (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Sub node.
ir_node * new_d_Sub (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct a Sub node.
ir_node * new_Sub (ir_node *irn_left, ir_node *irn_right)
Construct a Sub node.
int is_Sub (const ir_node *node)
Test if node is a Sub.
ir_node * get_Sub_left (const ir_node *node)
Returns left input of a Sub node.
void set_Sub_left (ir_node *node, ir_node *left)
Sets left input of a Sub node.
ir_node * get_Sub_right (const ir_node *node)
Returns right input of a Sub node.
void set_Sub_right (ir_node *node, ir_node *right)
Sets right input of a Sub node.
ir_op * get_op_Sub (void)
Returns opcode for Sub nodes.
Variables
ir_op * op_Sub
Sub opcode.
Detailed Description
returns the difference of its operands
Enumeration Type Documentation
n_Sub
enum n_Sub
Input numbers for Sub node.
Enumerator
n_Sub_left
first operand
n_Sub_right
second operand
n_Sub_max
Definition at line 3946 of file nodes.h.
Function Documentation
get_op_Sub()
ir_op * get_op_Sub (void)
Returns opcode for Sub nodes.
Definition at line 2745 of file gen_irnode.c.
References op_Sub.
get_Sub_left()
ir_node * get_Sub_left (const ir_node * node)
Returns left input of a Sub node.
Definition at line 2725 of file gen_irnode.c.
get_Sub_right()
ir_node * get_Sub_right (const ir_node * node)
Returns right input of a Sub node.
Definition at line 2735 of file gen_irnode.c.
is_Sub()
int is_Sub (const ir_node * node)
Test if node is a Sub.
Returns
1 if the node is a Sub node, 0 otherwise
Definition at line 3517 of file gen_irnode.c.
new_d_Sub()
ir_node * new_d_Sub (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct a Sub node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 2713 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Sub().
Referenced by new_Sub().
new_r_Sub()
ir_node * new_r_Sub (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Sub node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 2708 of file gen_irnode.c.
References new_rd_Sub().
new_rd_Sub()
ir_node * new_rd_Sub (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Sub node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 2692 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), get_reference_offset_mode(), mode_is_reference(), new_ir_node(), op_Sub, optimize_node(), and verify_new_node().
Referenced by new_d_Sub(), and new_r_Sub().
new_Sub()
ir_node * new_Sub (ir_node * irn_left, ir_node * irn_right)
Construct a Sub node.
Parameters
irn_left left
irn_right right
Definition at line 2720 of file gen_irnode.c.
References new_d_Sub().
set_Sub_left()
void set_Sub_left (ir_node * node, ir_node * left)
Sets left input of a Sub node.
Definition at line 2730 of file gen_irnode.c.
set_Sub_right()
void set_Sub_right (ir_node * node, ir_node * right)
Sets right input of a Sub node.
Definition at line 2740 of file gen_irnode.c.
Variable Documentation
op_Sub
ir_op* op_Sub
Sub opcode.
Definition at line 4003 of file nodes.h.
Referenced by get_op_Sub(), and new_rd_Sub().