libFirm: Mulh node
Mulh node
Procedure Graph » Nodes
Enumerations
enum n_Mulh { n_Mulh_left , n_Mulh_right , n_Mulh_max = n_Mulh_right }
Input numbers for Mulh node.
Functions
ir_node * new_rd_Mulh (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Mulh node.
ir_node * new_r_Mulh (ir_node *block, ir_node *irn_left, ir_node *irn_right)
Construct a Mulh node.
ir_node * new_d_Mulh (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right)
Construct a Mulh node.
ir_node * new_Mulh (ir_node *irn_left, ir_node *irn_right)
Construct a Mulh node.
int is_Mulh (const ir_node *node)
Test if node is a Mulh.
ir_node * get_Mulh_left (const ir_node *node)
Returns left input of a Mulh node.
void set_Mulh_left (ir_node *node, ir_node *left)
Sets left input of a Mulh node.
ir_node * get_Mulh_right (const ir_node *node)
Returns right input of a Mulh node.
void set_Mulh_right (ir_node *node, ir_node *right)
Sets right input of a Mulh node.
ir_op * get_op_Mulh (void)
Returns opcode for Mulh nodes.
Variables
ir_op * op_Mulh
Mulh opcode.
Detailed Description
returns the upper word of the product of its operands (the part which would not fit into the result mode of a normal Mul anymore)
Enumeration Type Documentation
n_Mulh
enum n_Mulh
Input numbers for Mulh node.
Enumerator
n_Mulh_left
first operand
n_Mulh_right
second operand
n_Mulh_max
Definition at line 2594 of file nodes.h.
Function Documentation
get_Mulh_left()
ir_node * get_Mulh_left (const ir_node * node)
Returns left input of a Mulh node.
Definition at line 1763 of file gen_irnode.c.
get_Mulh_right()
ir_node * get_Mulh_right (const ir_node * node)
Returns right input of a Mulh node.
Definition at line 1773 of file gen_irnode.c.
get_op_Mulh()
ir_op * get_op_Mulh (void)
Returns opcode for Mulh nodes.
Definition at line 1783 of file gen_irnode.c.
References op_Mulh.
is_Mulh()
int is_Mulh (const ir_node * node)
Test if node is a Mulh.
Returns
1 if the node is a Mulh node, 0 otherwise
Definition at line 3347 of file gen_irnode.c.
new_d_Mulh()
ir_node * new_d_Mulh (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right)
Construct a Mulh node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
Definition at line 1751 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Mulh().
Referenced by new_Mulh().
new_Mulh()
ir_node * new_Mulh (ir_node * irn_left, ir_node * irn_right)
Construct a Mulh node.
Parameters
irn_left left
irn_right right
Definition at line 1758 of file gen_irnode.c.
References new_d_Mulh().
new_r_Mulh()
ir_node * new_r_Mulh (ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Mulh node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1746 of file gen_irnode.c.
References new_rd_Mulh().
new_rd_Mulh()
ir_node * new_rd_Mulh (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right)
Construct a Mulh node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
Definition at line 1730 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Mulh, optimize_node(), and verify_new_node().
Referenced by new_d_Mulh(), and new_r_Mulh().
set_Mulh_left()
void set_Mulh_left (ir_node * node, ir_node * left)
Sets left input of a Mulh node.
Definition at line 1768 of file gen_irnode.c.
set_Mulh_right()
void set_Mulh_right (ir_node * node, ir_node * right)
Sets right input of a Mulh node.
Definition at line 1778 of file gen_irnode.c.
Variable Documentation
op_Mulh
ir_op* op_Mulh
Mulh opcode.
Definition at line 2651 of file nodes.h.
Referenced by get_op_Mulh(), and new_rd_Mulh().