libFirm: Mux node
Mux node
Procedure Graph » Nodes
Enumerations
enum n_Mux { n_Mux_sel , n_Mux_false , n_Mux_true , n_Mux_max = n_Mux_true }
Input numbers for Mux node.
Functions
ir_node * new_rd_Mux (dbg_info *dbgi, ir_node *block, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_r_Mux (ir_node *block, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_d_Mux (dbg_info *dbgi, ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
ir_node * new_Mux (ir_node *irn_sel, ir_node *irn_false, ir_node *irn_true)
Construct a Mux node.
int is_Mux (const ir_node *node)
Test if node is a Mux.
ir_node * get_Mux_sel (const ir_node *node)
Returns sel input of a Mux node.
void set_Mux_sel (ir_node *node, ir_node *sel)
Sets sel input of a Mux node.
ir_node * get_Mux_false (const ir_node *node)
Returns false input of a Mux node.
void set_Mux_false (ir_node *node, ir_node *false_)
Sets false input of a Mux node.
ir_node * get_Mux_true (const ir_node *node)
Returns true input of a Mux node.
void set_Mux_true (ir_node *node, ir_node *true_)
Sets true input of a Mux node.
ir_op * get_op_Mux (void)
Returns opcode for Mux nodes.
Variables
ir_op * op_Mux
Mux opcode.
Detailed Description
returns the false or true operand depending on the value of the sel operand
Enumeration Type Documentation
n_Mux
enum n_Mux
Input numbers for Mux node.
Enumerator
n_Mux_sel
value making the output selection
n_Mux_false
selected if sel input is false
n_Mux_true
selected if sel input is true
n_Mux_max
Definition at line 2669 of file nodes.h.
Function Documentation
get_Mux_false()
ir_node * get_Mux_false (const ir_node * node)
Returns false input of a Mux node.
Definition at line 1832 of file gen_irnode.c.
get_Mux_sel()
ir_node * get_Mux_sel (const ir_node * node)
Returns sel input of a Mux node.
Definition at line 1822 of file gen_irnode.c.
get_Mux_true()
ir_node * get_Mux_true (const ir_node * node)
Returns true input of a Mux node.
Definition at line 1842 of file gen_irnode.c.
get_op_Mux()
ir_op * get_op_Mux (void)
Returns opcode for Mux nodes.
Definition at line 1852 of file gen_irnode.c.
References op_Mux.
is_Mux()
int is_Mux (const ir_node * node)
Test if node is a Mux.
Returns
1 if the node is a Mux node, 0 otherwise
Definition at line 3352 of file gen_irnode.c.
new_d_Mux()
ir_node * new_d_Mux (dbg_info * dbgi, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
dbgi A pointer to debug information.
irn_sel sel
irn_false false
irn_true true
Definition at line 1810 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Mux().
Referenced by new_Mux().
new_Mux()
ir_node * new_Mux (ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
irn_sel sel
irn_false false
irn_true true
Definition at line 1817 of file gen_irnode.c.
References new_d_Mux().
new_r_Mux()
ir_node * new_r_Mux (ir_node * block, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
block The IR block the node belongs to.
irn_sel sel
irn_false false
irn_true true
Definition at line 1805 of file gen_irnode.c.
References new_rd_Mux().
new_rd_Mux()
ir_node * new_rd_Mux (dbg_info * dbgi, ir_node * block, ir_node * irn_sel, ir_node * irn_false, ir_node * irn_true)
Construct a Mux node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_sel sel
irn_false false
irn_true true
Definition at line 1788 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), new_ir_node(), op_Mux, optimize_node(), and verify_new_node().
Referenced by new_d_Mux(), and new_r_Mux().
set_Mux_false()
void set_Mux_false (ir_node * node, ir_node * false_)
Sets false input of a Mux node.
Definition at line 1837 of file gen_irnode.c.
set_Mux_sel()
void set_Mux_sel (ir_node * node, ir_node * sel)
Sets sel input of a Mux node.
Definition at line 1827 of file gen_irnode.c.
set_Mux_true()
void set_Mux_true (ir_node * node, ir_node * true_)
Sets true input of a Mux node.
Definition at line 1847 of file gen_irnode.c.
Variable Documentation
op_Mux
ir_op* op_Mux
Mux opcode.
Definition at line 2735 of file nodes.h.
Referenced by get_op_Mux(), and new_rd_Mux().