libFirm: Tuple node
Tuple node
Procedure Graph » Nodes
Functions
ir_node * new_rd_Tuple (dbg_info *dbgi, ir_node *block, int arity, ir_node *const *in)
Construct a Tuple node.
ir_node * new_r_Tuple (ir_node *block, int arity, ir_node *const *in)
Construct a Tuple node.
ir_node * new_d_Tuple (dbg_info *dbgi, int arity, ir_node *const *in)
Construct a Tuple node.
ir_node * new_Tuple (int arity, ir_node *const *in)
Construct a Tuple node.
int is_Tuple (const ir_node *node)
Test if node is a Tuple.
int get_Tuple_n_preds (ir_node const *node)
Get the number of Tuple preds.
ir_node * get_Tuple_pred (ir_node const *node, int pos)
Get the Tuple pred with index pos.
void set_Tuple_pred (ir_node *node, int pos, ir_node *pred)
Set the Tuple pred with index pos.
ir_node ** get_Tuple_pred_arr (ir_node *node)
Get an array of all Tuple preds.
ir_op * get_op_Tuple (void)
Returns opcode for Tuple nodes.
Variables
ir_op * op_Tuple
Tuple opcode.
Detailed Description
Builds a Tuple from single values.
This is needed to implement optimizations that remove a node that produced a tuple. The node can be replaced by the Tuple operation so that the following Proj nodes have not to be changed. (They are hard to find due to the implementation with pointers in only one direction.) The Tuple node is smaller than any other node, so that a node can be changed into a Tuple by just changing its opcode and giving it a new in array.
Function Documentation
get_op_Tuple()
ir_op * get_op_Tuple (void)
Returns opcode for Tuple nodes.
Definition at line 2906 of file gen_irnode.c.
References op_Tuple.
get_Tuple_n_preds()
int get_Tuple_n_preds (ir_node const * node)
Get the number of Tuple preds.
Definition at line 2886 of file gen_irnode.c.
get_Tuple_pred()
ir_node * get_Tuple_pred (ir_node const * node, int pos)
Get the Tuple pred with index pos.
Definition at line 2891 of file gen_irnode.c.
get_Tuple_pred_arr()
ir_node ** get_Tuple_pred_arr (ir_node * node)
Get an array of all Tuple preds.
Definition at line 2901 of file gen_irnode.c.
is_Tuple()
int is_Tuple (const ir_node * node)
Test if node is a Tuple.
Returns
1 if the node is a Tuple node, 0 otherwise
Definition at line 3552 of file gen_irnode.c.
new_d_Tuple()
ir_node * new_d_Tuple (dbg_info * dbgi, int arity, ir_node *const * in)
Construct a Tuple node.
Parameters
dbgi A pointer to debug information.
arity size of additional inputs array
in additional inputs
Definition at line 2874 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Tuple().
Referenced by new_Tuple().
new_r_Tuple()
ir_node * new_r_Tuple (ir_node * block, int arity, ir_node *const * in)
Construct a Tuple node.
Parameters
block The IR block the node belongs to.
arity size of additional inputs array
in additional inputs
Definition at line 2869 of file gen_irnode.c.
References new_rd_Tuple().
new_rd_Tuple()
ir_node * new_rd_Tuple (dbg_info * dbgi, ir_node * block, int arity, ir_node *const * in)
Construct a Tuple node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
arity size of additional inputs array
in additional inputs
Definition at line 2855 of file gen_irnode.c.
References get_irn_irg(), mode_T, new_ir_node(), op_Tuple, optimize_node(), and verify_new_node().
Referenced by new_d_Tuple(), and new_r_Tuple().
new_Tuple()
ir_node * new_Tuple (int arity, ir_node *const * in)
Construct a Tuple node.
Parameters
arity size of additional inputs array
in additional inputs
Definition at line 2881 of file gen_irnode.c.
References new_d_Tuple().
set_Tuple_pred()
void set_Tuple_pred (ir_node * node, int pos, ir_node * pred)
Set the Tuple pred with index pos.
Definition at line 2896 of file gen_irnode.c.
Variable Documentation
op_Tuple
ir_op* op_Tuple
Tuple opcode.
Definition at line 4238 of file nodes.h.
Referenced by get_op_Tuple(), and new_rd_Tuple().