libFirm: Free node
Free node
Procedure Graph » Nodes
Enumerations
enum n_Free { n_Free_mem , n_Free_ptr , n_Free_max = n_Free_ptr }
Input numbers for Free node.
Functions
ir_node * new_rd_Free (dbg_info *dbgi, ir_node *block, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_r_Free (ir_node *block, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_d_Free (dbg_info *dbgi, ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
ir_node * new_Free (ir_node *irn_mem, ir_node *irn_ptr)
Construct a Free node.
int is_Free (const ir_node *node)
Test if node is a Free.
ir_node * get_Free_mem (const ir_node *node)
Returns mem input of a Free node.
void set_Free_mem (ir_node *node, ir_node *mem)
Sets mem input of a Free node.
ir_node * get_Free_ptr (const ir_node *node)
Returns ptr input of a Free node.
void set_Free_ptr (ir_node *node, ir_node *ptr)
Sets ptr input of a Free node.
ir_op * get_op_Free (void)
Returns opcode for Free nodes.
Variables
ir_op * op_Free
Free opcode.
Detailed Description
Frees a block of memory previously allocated by an Alloc node
Enumeration Type Documentation
n_Free
enum n_Free
Input numbers for Free node.
Enumerator
n_Free_mem
memory dependency
n_Free_ptr
pointer to the object to free
n_Free_max
Definition at line 1923 of file nodes.h.
Function Documentation
get_Free_mem()
ir_node * get_Free_mem (const ir_node * node)
Returns mem input of a Free node.
Definition at line 1318 of file gen_irnode.c.
get_Free_ptr()
ir_node * get_Free_ptr (const ir_node * node)
Returns ptr input of a Free node.
Definition at line 1328 of file gen_irnode.c.
get_op_Free()
ir_op * get_op_Free (void)
Returns opcode for Free nodes.
Definition at line 1338 of file gen_irnode.c.
References op_Free.
is_Free()
int is_Free (const ir_node * node)
Test if node is a Free.
Returns
1 if the node is a Free node, 0 otherwise
Definition at line 3242 of file gen_irnode.c.
new_d_Free()
ir_node * new_d_Free (dbg_info * dbgi, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
dbgi A pointer to debug information.
irn_mem mem
irn_ptr ptr
Definition at line 1306 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Free().
Referenced by new_Free().
new_Free()
ir_node * new_Free (ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
irn_mem mem
irn_ptr ptr
Definition at line 1313 of file gen_irnode.c.
References new_d_Free().
new_r_Free()
ir_node * new_r_Free (ir_node * block, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
block The IR block the node belongs to.
irn_mem mem
irn_ptr ptr
Definition at line 1301 of file gen_irnode.c.
References new_rd_Free().
new_rd_Free()
ir_node * new_rd_Free (dbg_info * dbgi, ir_node * block, ir_node * irn_mem, ir_node * irn_ptr)
Construct a Free node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_mem mem
irn_ptr ptr
Definition at line 1285 of file gen_irnode.c.
References get_irn_irg(), mode_M, new_ir_node(), op_Free, optimize_node(), and verify_new_node().
Referenced by new_d_Free(), and new_r_Free().
set_Free_mem()
void set_Free_mem (ir_node * node, ir_node * mem)
Sets mem input of a Free node.
Definition at line 1323 of file gen_irnode.c.
set_Free_ptr()
void set_Free_ptr (ir_node * node, ir_node * ptr)
Sets ptr input of a Free node.
Definition at line 1333 of file gen_irnode.c.
Variable Documentation
op_Free
ir_op* op_Free
Free opcode.
Definition at line 1980 of file nodes.h.
Referenced by get_op_Free(), and new_rd_Free().