libFirm: NoMem node
NoMem node
Procedure Graph » Nodes
Functions
ir_node * new_rd_NoMem (dbg_info *dbgi, ir_graph *irg)
Construct a NoMem node.
ir_node * new_r_NoMem (ir_graph *irg)
Construct a NoMem node.
ir_node * new_d_NoMem (dbg_info *dbgi)
Construct a NoMem node.
ir_node * new_NoMem (void)
Construct a NoMem node.
int is_NoMem (const ir_node *node)
Test if node is a NoMem.
ir_op * get_op_NoMem (void)
Returns opcode for NoMem nodes.
Variables
ir_op * op_NoMem
NoMem opcode.
Detailed Description
Placeholder node for cases where you don't need any memory input
Function Documentation
get_op_NoMem()
ir_op * get_op_NoMem (void)
Returns opcode for NoMem nodes.
Definition at line 1887 of file gen_irnode.c.
References op_NoMem.
is_NoMem()
int is_NoMem (const ir_node * node)
Test if node is a NoMem.
Returns
1 if the node is a NoMem node, 0 otherwise
Definition at line 3357 of file gen_irnode.c.
new_d_NoMem()
ir_node * new_d_NoMem (dbg_info * dbgi)
Construct a NoMem node.
Parameters
dbgi A pointer to debug information.
Definition at line 1875 of file gen_irnode.c.
References current_ir_graph, IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_NoMem().
Referenced by new_NoMem().
new_NoMem()
ir_node * new_NoMem (void)
Construct a NoMem node.
Definition at line 1882 of file gen_irnode.c.
References new_d_NoMem().
new_r_NoMem()
ir_node * new_r_NoMem (ir_graph * irg)
Construct a NoMem node.
Parameters
irg The IR graph the node belongs to.
Definition at line 1870 of file gen_irnode.c.
References new_rd_NoMem().
new_rd_NoMem()
ir_node * new_rd_NoMem (dbg_info * dbgi, ir_graph * irg)
Construct a NoMem node.
Parameters
dbgi A pointer to debug information.
irg The IR graph the node belongs to.
Definition at line 1857 of file gen_irnode.c.
References get_irg_start_block(), mode_M, new_ir_node(), op_NoMem, optimize_node(), and verify_new_node().
Referenced by new_d_NoMem(), and new_r_NoMem().
Variable Documentation
op_NoMem
ir_op* op_NoMem
NoMem opcode.
Definition at line 2784 of file nodes.h.
Referenced by get_op_NoMem(), and new_rd_NoMem().