libFirm: CopyB node
CopyB node
Procedure Graph » Nodes
Enumerations
enum n_CopyB { n_CopyB_mem , n_CopyB_dst , n_CopyB_src , n_CopyB_max = n_CopyB_src }
Input numbers for CopyB node.
Functions
ir_node * new_rd_CopyB (dbg_info *dbgi, ir_node *block, ir_node *irn_mem, ir_node *irn_dst, ir_node *irn_src, ir_type *type, ir_cons_flags flags)
Construct a CopyB node.
ir_node * new_r_CopyB (ir_node *block, ir_node *irn_mem, ir_node *irn_dst, ir_node *irn_src, ir_type *type, ir_cons_flags flags)
Construct a CopyB node.
ir_node * new_d_CopyB (dbg_info *dbgi, ir_node *irn_mem, ir_node *irn_dst, ir_node *irn_src, ir_type *type, ir_cons_flags flags)
Construct a CopyB node.
ir_node * new_CopyB (ir_node *irn_mem, ir_node *irn_dst, ir_node *irn_src, ir_type *type, ir_cons_flags flags)
Construct a CopyB node.
int is_CopyB (const ir_node *node)
Test if node is a CopyB.
ir_node * get_CopyB_mem (const ir_node *node)
Returns mem input of a CopyB node.
void set_CopyB_mem (ir_node *node, ir_node *mem)
Sets mem input of a CopyB node.
ir_node * get_CopyB_dst (const ir_node *node)
Returns dst input of a CopyB node.
void set_CopyB_dst (ir_node *node, ir_node *dst)
Sets dst input of a CopyB node.
ir_node * get_CopyB_src (const ir_node *node)
Returns src input of a CopyB node.
void set_CopyB_src (ir_node *node, ir_node *src)
Sets src input of a CopyB node.
ir_type * get_CopyB_type (const ir_node *node)
Returns type attribute of a CopyB node.
void set_CopyB_type (ir_node *node, ir_type *type)
Sets type attribute of a CopyB node.
ir_volatility get_CopyB_volatility (const ir_node *node)
Returns volatility attribute of a CopyB node.
void set_CopyB_volatility (ir_node *node, ir_volatility volatility)
Sets volatility attribute of a CopyB node.
ir_op * get_op_CopyB (void)
Returns opcode for CopyB nodes.
Variables
ir_op * op_CopyB
CopyB opcode.
Detailed Description
Copies a block of memory with statically known size/type.
Enumeration Type Documentation
n_CopyB
enum n_CopyB
Input numbers for CopyB node.
Enumerator
n_CopyB_mem
memory dependency
n_CopyB_dst
destination address
n_CopyB_src
source address
n_CopyB_max
Definition at line 1494 of file nodes.h.
Function Documentation
get_CopyB_dst()
ir_node * get_CopyB_dst (const ir_node * node)
Returns dst input of a CopyB node.
Definition at line 1034 of file gen_irnode.c.
get_CopyB_mem()
ir_node * get_CopyB_mem (const ir_node * node)
Returns mem input of a CopyB node.
Definition at line 1024 of file gen_irnode.c.
get_CopyB_src()
ir_node * get_CopyB_src (const ir_node * node)
Returns src input of a CopyB node.
Definition at line 1044 of file gen_irnode.c.
get_CopyB_type()
ir_type * get_CopyB_type (const ir_node * node)
Returns type attribute of a CopyB node.
Definition at line 3177 of file gen_irnode.c.
get_CopyB_volatility()
ir_volatility get_CopyB_volatility (const ir_node * node)
Returns volatility attribute of a CopyB node.
Definition at line 3187 of file gen_irnode.c.
get_op_CopyB()
ir_op * get_op_CopyB (void)
Returns opcode for CopyB nodes.
Definition at line 1054 of file gen_irnode.c.
References op_CopyB.
is_CopyB()
int is_CopyB (const ir_node * node)
Test if node is a CopyB.
Returns
1 if the node is a CopyB node, 0 otherwise
Definition at line 3172 of file gen_irnode.c.
new_CopyB()
ir_node * new_CopyB (ir_node * irn_mem, ir_node * irn_dst, ir_node * irn_src, ir_type * type, ir_cons_flags flags)
Construct a CopyB node.
Parameters
irn_mem mem
irn_dst dst
irn_src src
type type of copied data
flags specifies volatility
Definition at line 1019 of file gen_irnode.c.
References new_d_CopyB().
new_d_CopyB()
ir_node * new_d_CopyB (dbg_info * dbgi, ir_node * irn_mem, ir_node * irn_dst, ir_node * irn_src, ir_type * type, ir_cons_flags flags)
Construct a CopyB node.
Parameters
dbgi A pointer to debug information.
irn_mem mem
irn_dst dst
irn_src src
type type of copied data
flags specifies volatility
Definition at line 1012 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_CopyB().
Referenced by new_CopyB().
new_r_CopyB()
ir_node * new_r_CopyB (ir_node * block, ir_node * irn_mem, ir_node * irn_dst, ir_node * irn_src, ir_type * type, ir_cons_flags flags)
Construct a CopyB node.
Parameters
block The IR block the node belongs to.
irn_mem mem
irn_dst dst
irn_src src
type type of copied data
flags specifies volatility
Definition at line 1007 of file gen_irnode.c.
References new_rd_CopyB().
new_rd_CopyB()
ir_node * new_rd_CopyB (dbg_info * dbgi, ir_node * block, ir_node * irn_mem, ir_node * irn_dst, ir_node * irn_src, ir_type * type, ir_cons_flags flags)
Construct a CopyB node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_mem mem
irn_dst dst
irn_src src
type type of copied data
flags specifies volatility
Definition at line 988 of file gen_irnode.c.
References cons_volatile, get_irn_irg(), mode_M, new_ir_node(), op_CopyB, optimize_node(), and verify_new_node().
Referenced by new_d_CopyB(), and new_r_CopyB().
set_CopyB_dst()
void set_CopyB_dst (ir_node * node, ir_node * dst)
Sets dst input of a CopyB node.
Definition at line 1039 of file gen_irnode.c.
set_CopyB_mem()
void set_CopyB_mem (ir_node * node, ir_node * mem)
Sets mem input of a CopyB node.
Definition at line 1029 of file gen_irnode.c.
set_CopyB_src()
void set_CopyB_src (ir_node * node, ir_node * src)
Sets src input of a CopyB node.
Definition at line 1049 of file gen_irnode.c.
set_CopyB_type()
void set_CopyB_type (ir_node * node, ir_type * type)
Sets type attribute of a CopyB node.
Definition at line 3182 of file gen_irnode.c.
set_CopyB_volatility()
void set_CopyB_volatility (ir_node * node, ir_volatility volatility)
Sets volatility attribute of a CopyB node.
Definition at line 3192 of file gen_irnode.c.
Variable Documentation
op_CopyB
ir_op* op_CopyB
CopyB opcode.
Definition at line 1578 of file nodes.h.
Referenced by get_op_CopyB(), and new_rd_CopyB().