libFirm: Mod node
Mod node
Procedure Graph » Nodes
Enumerations
enum n_Mod { n_Mod_mem , n_Mod_left , n_Mod_right , n_Mod_max = n_Mod_right }
Input numbers for Mod node.
enum pn_Mod {
pn_Mod_M , pn_Mod_res , pn_Mod_X_regular , pn_Mod_X_except ,
pn_Mod_max = pn_Mod_X_except
}
Projection numbers for result of Mod node (use for Proj nodes)
Functions
ir_node * new_rd_Mod (dbg_info *dbgi, ir_node *block, ir_node *irn_mem, ir_node *irn_left, ir_node *irn_right, int pinned)
Construct a Mod node.
ir_node * new_r_Mod (ir_node *block, ir_node *irn_mem, ir_node *irn_left, ir_node *irn_right, int pinned)
Construct a Mod node.
ir_node * new_d_Mod (dbg_info *dbgi, ir_node *irn_mem, ir_node *irn_left, ir_node *irn_right, int pinned)
Construct a Mod node.
ir_node * new_Mod (ir_node *irn_mem, ir_node *irn_left, ir_node *irn_right, int pinned)
Construct a Mod node.
int is_Mod (const ir_node *node)
Test if node is a Mod.
ir_node * get_Mod_mem (const ir_node *node)
Returns mem input of a Mod node.
void set_Mod_mem (ir_node *node, ir_node *mem)
Sets mem input of a Mod node.
ir_node * get_Mod_left (const ir_node *node)
Returns left input of a Mod node.
void set_Mod_left (ir_node *node, ir_node *left)
Sets left input of a Mod node.
ir_node * get_Mod_right (const ir_node *node)
Returns right input of a Mod node.
void set_Mod_right (ir_node *node, ir_node *right)
Sets right input of a Mod node.
ir_mode * get_Mod_resmode (const ir_node *node)
Returns resmode attribute of a Mod node.
void set_Mod_resmode (ir_node *node, ir_mode *resmode)
Sets resmode attribute of a Mod node.
ir_op * get_op_Mod (void)
Returns opcode for Mod nodes.
Variables
ir_op * op_Mod
Mod opcode.
Detailed Description
returns the remainder of its operands from an implied division.
Examples:
mod(5,3) produces 2 mod(5,-3) produces 2 mod(-5,3) produces -2 mod(-5,-3) produces -2
Enumeration Type Documentation
n_Mod
enum n_Mod
Input numbers for Mod node.
Enumerator
n_Mod_mem
memory dependency
n_Mod_left
first operand
n_Mod_right
second operand
n_Mod_max
Definition at line 2416 of file nodes.h.
pn_Mod
enum pn_Mod
Projection numbers for result of Mod node (use for Proj nodes)
Enumerator
pn_Mod_M
memory result
pn_Mod_res
result of computation
pn_Mod_X_regular
control flow when no exception occurs
pn_Mod_X_except
control flow when exception occurred
pn_Mod_max
Definition at line 2426 of file nodes.h.
Function Documentation
get_Mod_left()
ir_node * get_Mod_left (const ir_node * node)
Returns left input of a Mod node.
Definition at line 1647 of file gen_irnode.c.
get_Mod_mem()
ir_node * get_Mod_mem (const ir_node * node)
Returns mem input of a Mod node.
Definition at line 1637 of file gen_irnode.c.
get_Mod_resmode()
ir_mode * get_Mod_resmode (const ir_node * node)
Returns resmode attribute of a Mod node.
Definition at line 3332 of file gen_irnode.c.
get_Mod_right()
ir_node * get_Mod_right (const ir_node * node)
Returns right input of a Mod node.
Definition at line 1657 of file gen_irnode.c.
get_op_Mod()
ir_op * get_op_Mod (void)
Returns opcode for Mod nodes.
Definition at line 1667 of file gen_irnode.c.
References op_Mod.
is_Mod()
int is_Mod (const ir_node * node)
Test if node is a Mod.
Returns
1 if the node is a Mod node, 0 otherwise
Definition at line 3327 of file gen_irnode.c.
new_d_Mod()
ir_node * new_d_Mod (dbg_info * dbgi, ir_node * irn_mem, ir_node * irn_left, ir_node * irn_right, int pinned)
Construct a Mod node.
Parameters
dbgi A pointer to debug information.
irn_mem mem
irn_left left
irn_right right
pinned pinned state
Definition at line 1625 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Mod().
Referenced by new_Mod().
new_Mod()
ir_node * new_Mod (ir_node * irn_mem, ir_node * irn_left, ir_node * irn_right, int pinned)
Construct a Mod node.
Parameters
irn_mem mem
irn_left left
irn_right right
pinned pinned state
Definition at line 1632 of file gen_irnode.c.
References new_d_Mod().
new_r_Mod()
ir_node * new_r_Mod (ir_node * block, ir_node * irn_mem, ir_node * irn_left, ir_node * irn_right, int pinned)
Construct a Mod node.
Parameters
block The IR block the node belongs to.
irn_mem mem
irn_left left
irn_right right
pinned pinned state
Definition at line 1620 of file gen_irnode.c.
References new_rd_Mod().
new_rd_Mod()
ir_node * new_rd_Mod (dbg_info * dbgi, ir_node * block, ir_node * irn_mem, ir_node * irn_left, ir_node * irn_right, int pinned)
Construct a Mod node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_mem mem
irn_left left
irn_right right
pinned pinned state
Definition at line 1600 of file gen_irnode.c.
References get_irn_irg(), get_irn_mode(), mode_T, new_ir_node(), op_Mod, optimize_node(), and verify_new_node().
Referenced by new_d_Mod(), and new_r_Mod().
set_Mod_left()
void set_Mod_left (ir_node * node, ir_node * left)
Sets left input of a Mod node.
Definition at line 1652 of file gen_irnode.c.
set_Mod_mem()
void set_Mod_mem (ir_node * node, ir_node * mem)
Sets mem input of a Mod node.
Definition at line 1642 of file gen_irnode.c.
set_Mod_resmode()
void set_Mod_resmode (ir_node * node, ir_mode * resmode)
Sets resmode attribute of a Mod node.
Definition at line 3337 of file gen_irnode.c.
set_Mod_right()
void set_Mod_right (ir_node * node, ir_node * right)
Sets right input of a Mod node.
Definition at line 1662 of file gen_irnode.c.
Variable Documentation
op_Mod
ir_op* op_Mod
Mod opcode.
Definition at line 2502 of file nodes.h.
Referenced by get_op_Mod(), and new_rd_Mod().