libFirm: Eor node
Eor node
Nodes
returns the result of a bitwise exclusive or operation of its operands.
Enumerations
enum n_Eor { n_Eor_left, n_Eor_right, n_Eor_max = n_Eor_right }
Input numbers for Eor node.
Functions
ir_node * new_rd_Eor (dbg_info *dbgi, ir_node *block, ir_node *irn_left, ir_node *irn_right, ir_mode *mode)
Construct an Eor node.
ir_node * new_r_Eor (ir_node *block, ir_node *irn_left, ir_node *irn_right, ir_mode *mode)
Construct an Eor node.
ir_node * new_d_Eor (dbg_info *dbgi, ir_node *irn_left, ir_node *irn_right, ir_mode *mode)
Construct an Eor node.
ir_node * new_Eor (ir_node *irn_left, ir_node *irn_right, ir_mode *mode)
Construct an Eor node.
int is_Eor (const ir_node *node)
Test if node is a Eor.
ir_node * get_Eor_left (const ir_node *node)
Returns left input of an Eor node.
void set_Eor_left (ir_node *node, ir_node *left)
Sets left input of an Eor node.
ir_node * get_Eor_right (const ir_node *node)
Returns right input of an Eor node.
void set_Eor_right (ir_node *node, ir_node *right)
Sets right input of an Eor node.
ir_op * get_op_Eor (void)
Returns opcode for Eor nodes.
Variables
ir_op * op_Eor
Eor opcode.
Detailed Description
returns the result of a bitwise exclusive or operation of its operands.
This is also known as the Xor operation.
Enumeration Type Documentation
enum n_Eor
Input numbers for Eor node.
Enumerator
n_Eor_left
first operand
n_Eor_right
second operand
n_Eor_max
Definition at line 1789 of file nodes.h.
Function Documentation
ir_node* get_Eor_left (const ir_node * node)
Returns left input of an Eor node.
Definition at line 1212 of file gen_irnode.c.
ir_node* get_Eor_right (const ir_node * node)
Returns right input of an Eor node.
Definition at line 1222 of file gen_irnode.c.
ir_op* get_op_Eor (void)
Returns opcode for Eor nodes.
Definition at line 1232 of file gen_irnode.c.
References op_Eor.
int is_Eor (const ir_node * node)
Test if node is a Eor.
Returns
1 if the node is a Eor node, 0 otherwise
Definition at line 3199 of file gen_irnode.c.
ir_node* new_d_Eor (dbg_info * dbgi, ir_node * irn_left, ir_node * irn_right, ir_mode * mode)
Construct an Eor node.
Parameters
dbgi A pointer to debug information.
irn_left left
irn_right right
mode mode of the operations result
Definition at line 1200 of file gen_irnode.c.
References current_ir_graph, get_cur_block(), IR_GRAPH_CONSTRAINT_CONSTRUCTION, irg_is_constrained(), and new_rd_Eor().
Referenced by new_Eor().
ir_node* new_Eor (ir_node * irn_left, ir_node * irn_right, ir_mode * mode)
Construct an Eor node.
Parameters
irn_left left
irn_right right
mode mode of the operations result
Definition at line 1207 of file gen_irnode.c.
References new_d_Eor().
ir_node* new_r_Eor (ir_node * block, ir_node * irn_left, ir_node * irn_right, ir_mode * mode)
Construct an Eor node.
Parameters
block The IR block the node belongs to.
irn_left left
irn_right right
mode mode of the operations result
Definition at line 1195 of file gen_irnode.c.
References new_rd_Eor().
ir_node* new_rd_Eor (dbg_info * dbgi, ir_node * block, ir_node * irn_left, ir_node * irn_right, ir_mode * mode)
Construct an Eor node.
Parameters
dbgi A pointer to debug information.
block The IR block the node belongs to.
irn_left left
irn_right right
mode mode of the operations result
Definition at line 1179 of file gen_irnode.c.
References get_irn_irg(), new_ir_node(), op_Eor, optimize_node(), and verify_new_node().
Referenced by new_d_Eor(), and new_r_Eor().
void set_Eor_left (ir_node * node, ir_node * left)
Sets left input of an Eor node.
Definition at line 1217 of file gen_irnode.c.
void set_Eor_right (ir_node * node, ir_node * right)
Sets right input of an Eor node.
Definition at line 1227 of file gen_irnode.c.
Variable Documentation
ir_op* op_Eor
Eor opcode.
Definition at line 1850 of file nodes.h.
Referenced by get_op_Eor(), and new_rd_Eor().